from typing import Any, Protocol

ActivityRecord = dict[str, Any]
SummaryData = dict[str, Any]


class MetricCalculator(Protocol):
    def calculate(self, activities: list[ActivityRecord]) -> SummaryData: ...


class SummaryBuilder(Protocol):
    def reset(self) -> None: ...

    def add_distance(self, value: float) -> None: ...

    def add_moving_time(self, value: str) -> None: ...

    def add_elevation_gain(self, value: float) -> None: ...

    def add_heart_rate_metrics(self, average: float, maximum: float, /) -> None: ...

    def add_calories(self, value: float) -> None: ...

    def add_perceived_exertion(self, value: float) -> None: ...

    def get_summary(self) -> SummaryData: ...


class ActivityDataLoader(Protocol):
    def load_activities(self) -> list[ActivityRecord]: ...


class ActivitySummaryPresenter(Protocol):
    def present_weekly_report(self, summary: SummaryData) -> None: ...
