name: Testing the app

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read
  packages: write

jobs:
  # Run tests
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Set up uv with cache
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.14"
          enable-cache: true

      - name: Run tests
        run: uv run pytest tests/

  # Lint code with ruff
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Set up uv with cache
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.16"
          enable-cache: true

      - name: Lint code with Ruff
        run: uv run ruff check . --fix

  # Static type check with mypy
  typecheck:
    name: Type Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Set up uv with cache
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.16"
          enable-cache: true

      - name: Type check with mypy
        run: uv run mypy .

  # Build and push Docker image
  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: [test, lint, typecheck]

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/alexalgarate/strava_analisys:latest
