name: Testing the app

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python and uv (with caching)
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.14"
          python-version-file: ".python-version"
          enable-cache: true

      - name: Run tests
        run: uv run pytest tests/ 
        

      - name: Lint code with Ruff
        run: uv run ruff check . --fix

      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/alexalgarate/strava_analisys:latest
        

        env:
          DOCKER_BUILDKIT: 1
          GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}